### PR TITLE
Disable send button when there are no forms

### PR DESCRIPTION
**Pull request by iadeelzafar**
### Changes:

1- Disable the Send button at first
2- OnLoadFinished, when setEmptyViewVisibility is called, if no. of results is greater than 0, enable the Send button.

### CODE REVIEW

**Comment by iadeelzafar** [comment]
Hi @shobhitagarwal1612 @lakshyagupta21 , Please review this.

**Comment by iadeelzafar** [comment]
@shobhitagarwal1612 That's because I reformatted the code. Except the reformatting if there any other unrelated changes, let me know.

**Comment by shobhitagarwal1612** [comment]
> Except the reformatting if there any other unrelated changes, let me know.

Just the reformatting part

**Comment by iadeelzafar** [comment]
@shobhitagarwal1612 Okay. I'll undo the reformatting.

**Comment by iadeelzafar** [comment]
@shobhitagarwal1612 It's done.

**Pull request merged**
