### PR TITLE
Dialog added before hotspot is stopped

### LINKED ISSUE #72: Rotating send screen causes hotspot to be recreated
Sometimes it fails, sometimes it succeeds. Ideally the existing one could just be used.

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Closes #72 

Screen orientation issue resolved and added a dialog before turning the hotspot off so that user can know that leaving the activity may stop the connection.

For future, we can have an option to run the hotspot connection throughout the activities.

### CODE REVIEW

**Comment by lognaturel** [comment]
This looks good to me and I think it would be good to merge before the 1.0 release. @shobhitagarwal1612 do you want to take a quick look?

**Comment by lognaturel** [comment]
Rotation on the main screen now leads to:

```
E/AndroidRuntime(14321): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.odk.share/org.odk.share.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.odk.share.adapters.FormsAdapter.changeCursor(android.database.Cursor)' on a null object reference
E/AndroidRuntime(14321): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3151)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5205)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.access$1100(ActivityThread.java:219)
E/AndroidRuntime(14321): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
E/AndroidRuntime(14321): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14321): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.main(ActivityThread.java:6939)
E/AndroidRuntime(14321): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14321): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14321): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(14321): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(14321): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.odk.share.adapters.FormsAdapter.changeCursor(android.database.Cursor)' on a null object reference
E/AndroidRuntime(14321): 	at org.odk.share.activities.MainActivity.onLoadFinished(MainActivity.java:125)
E/AndroidRuntime(14321): 	at org.odk.share.activities.MainActivity.onLoadFinished(MainActivity.java:28)
E/AndroidRuntime(14321): 	at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:248)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
E/AndroidRuntime(14321): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:188)
E/AndroidRuntime(14321): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:173)
E/AndroidRuntime(14321): 	at android.support.v4.content.Loader.deliverResult(Loader.java:130)
E/AndroidRuntime(14321): 	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:107)
E/AndroidRuntime(14321): 	at android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:153)
E/AndroidRuntime(14321): 	at android.support.v4.content.Loader.startLoading(Loader.java:283)
E/AndroidRuntime(14321): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:76)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
E/AndroidRuntime(14321): 	at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
E/AndroidRuntime(14321): 	at android.app.Fragment.performStart(Fragment.java:2138)
E/AndroidRuntime(14321): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
E/AndroidRuntime(14321): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
E/AndroidRuntime(14321): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1065)
E/AndroidRuntime(14321): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1892)
E/AndroidRuntime(14321): 	at android.app.Activity.performStart(Activity.java:6658)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
```

**Comment by shobhitagarwal1612** [comment]
I get a crash if I try to click on any form name on the main screen

```
    Process: org.odk.share, PID: 3585
    java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetLong(Native Method)
        at android.database.CursorWindow.getLong(CursorWindow.java:511)
        at android.database.CursorWindow.getInt(CursorWindow.java:578)
        at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
        at android.database.CursorWrapper.getInt(CursorWrapper.java:122)
        at org.odk.share.dao.TransferDao.getInstancesFromCursor(TransferDao.java:88)
        at org.odk.share.fragments.StatisticsFragment.onResume(StatisticsFragment.java:92)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6127)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6127)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6127)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6127)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6127)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6127)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:694)
        at android.view.View.measure(View.java:19978)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2405)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1457)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1720)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1333)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6675)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
        at android.view.Choreographer.doCallbacks(Choreographer.java:699)
        at android.view.Choreographer.doFrame(Choreographer.java:634)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by lognaturel** [comment]
Whoops, I was on the wrong branch. Added at https://github.com/opendatakit/share/pull/82#issuecomment-412363181

**Pull request merged**
