### PR TITLE
Support lower android versions

### LINKED ISSUE #51: If portable hotspot configuration fails, no feedback is given
On two of the devices I've tried (Galaxy Tab A and Alcatel One Touch 5020D, details at https://github.com/opendatakit/collect#contributing-testing), when I tap "Send" and select filled forms, I go straight to a screen that shows "Waiting for connection to accept". What does this state means? It looks like it's not possible to set up a hostpot on those devices? I don't get promtped to enable from the settings.

On the Moto G4 I do get prompted to enable the hotspot from settings. Then I see the QR code and port number information.

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Fixes #51 
`CHANGE_NETWORK_STATE` Permission added for Android version 5.1.1

### CODE REVIEW

**Comment by lognaturel** [comment]
This definitely helps! Now I get the same sequencing problem as described in https://github.com/opendatakit/share/issues/51#issuecomment-406155689 -- the queued event is sent before the event subscription.

**Comment by lakshyagupta21** [comment]
@lognaturel Please check whether the commit works fine or not.

**Comment by lognaturel** [comment]
Yes, that does it!

**Comment by lognaturel** [comment]
After afa5794, the Alcatel / Android 4.1.1 device receiving doesn't crash but it hangs on the "Connecting to wifi" dialog. Before that it flashes a "already connected" toast. 

After a while I got:
```
07-19 21:48:28.886 13902-13902/org.odk.share E/WifiActivity: java.lang.IllegalArgumentException: Receiver not registered: org.odk.share.activities.WifiActivity$8@417e6710
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1214)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
        at org.odk.share.activities.WifiActivity.onStop(WifiActivity.java:183)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1210)
        at android.app.Activity.performStop(Activity.java:5158)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:3289)
        at android.app.ActivityThread.access$2700(ActivityThread.java:181)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5042)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lognaturel** [comment]
I think this is ready for merge and #57 can be tracked separately.

**Pull request merged**
