### PR TITLE
Move Collect related classes into a new package & update models

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
The intention is to separate the entire codebase of Share from Collect's Form/Instance models. This makes it easier to maintain those classes in case they are updated in Collect.

This also updates the models to the latest version

### CODE REVIEW

**Comment by lakshyagupta21** [comment]
There are some conflicts, resolve this then we're good to go.

**Comment by shobhitagarwal1612** [comment]
Sorry for the missing WIP tag. I haven't tested the branch yet and some more changes are coming

**Comment by lakshyagupta21** [comment]
Cool. I thought no more changes were there.

**Comment by shobhitagarwal1612** [comment]
@lakshyagupta21 Please review

**Comment by shobhitagarwal1612** [comment]
Did you test by sending a form/instance as well?

**Comment by lakshyagupta21** [comment]
yes, I tried sending both blank as well as filled form.

**Pull request merged**
